core/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'core'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

tracker/urls.py
from django.urls import include, path
from rest_framework import routers

from tracker import views

app_name = 'tracker'

router = routers.DefaultRouter()
router.register(r'trackers', views.TrackerList)
router.register(r'records', views.RecordList)

urlpatterns = [
    path('', views.TrackersView.as_view(), name='trackers'),
    path('create', views.create_tracker, name='create_tracker'),
    path('<int:pk>/', views.TrackerDetailView.as_view(), name='tracker_detail'),
    path('<int:tracker_id>/create_record', views.add_record, name='tracker_create_record'),
    path('api/', include(router.urls)),
]

training/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from core.views import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='home/login.html', authentication_form=LoginForm),
        name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('weather/', include('weather_statistics.urls')),
    path('tracker/', include(('tracker.urls', 'tracker'), namespace='tracker'))
]

tracker/models.py
from django.db import models


# Create your models here.
class Track(models.Model):
    name = models.CharField(max_length=30, unique=True)
    unit = models.CharField(max_length=30)
    description = models.CharField(max_length=300)

    def __str__(self):
        return "Track{name='%s', unit='%s', description='%s'}" % (self.name, self.unit, self.description)


class Record(models.Model):
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    value = models.FloatField(default=0.0)
    date = models.DateTimeField()
    note = models.CharField(max_length=200, blank=True, default='')

    def __str__(self):
        return "Record{value='%s', date='%s', note='%s'}" % (self.value, self.date.__format__('%Y-%m-%d'), self.note)

tracker/forms.py
from django import forms


class TrackerForm(forms.Form):
    name = forms.CharField(label='Name', max_length=30, required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    unit = forms.CharField(label='Unit', max_length=10, required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Description', max_length=300, required=True,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}))


class RecordForm(forms.Form):
    value = forms.FloatField(label='Value', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))
    datetime = forms.DateTimeField(label='Datetime', required=True, input_formats=['%Y-%m-%d %H:%M', '%Y-%m-%d'],
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control', 'placeholder': 'YYYY-MM-DD (HH:MM)'}))
    note = forms.CharField(label='Note', required=False,
                           widget=forms.TextInput(
                               attrs={'class': 'form-control', 'placeholder': 'Optional'}))

tracker/views.py
# Create your views here.
from datetime import datetime

from django.db import IntegrityError, transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from rest_framework import viewsets
from rest_framework.decorators import permission_classes
from rest_framework.permissions import AllowAny

from tracker.forms import TrackerForm, RecordForm
from tracker.models import Track, Record
from tracker.serializers import TrackSerializer, RecordSerializer


class TrackersView(generic.ListView):
    model = Track
    template_name = 'tracker/trackers.html'
    context_object_name = 'trackers_list'

    def get_queryset(self):
        return Track.objects.all()

    def get_context_data(self, **kwargs):
        context = super(TrackersView, self).get_context_data()
        context['form'] = TrackerForm()
        return context


def create_tracker(request):
    new_track_form = TrackerForm(request.POST)
    if request.method == 'POST' and new_track_form.is_valid():
        tracker = Track()
        tracker.name = request.POST['name']
        tracker.unit = request.POST['unit']
        tracker.description = request.POST['description']
        try:
            with transaction.atomic():
                tracker.save()
        except IntegrityError:
            return render(request, 'tracker/trackers.html', {
                'trackers_list': Track.objects.all(),
                'form': TrackerForm(),
                'form_error': "Tracking with name '%s' already exists" % (request.POST['name']),
            })
        return HttpResponseRedirect(reverse('tracker:trackers'))
    else:
        fields = {
            'trackers_list': Track.objects.all(),
            'form': new_track_form,
        }

        if new_track_form.errors.get('name'):
            fields['name_error'] = new_track_form.errors.get('name')[0]
        if new_track_form.errors.get('unit'):
            fields['unit_error'] = new_track_form.errors.get('unit')[0]
        if new_track_form.errors.get('description'):
            fields['description_error'] = new_track_form.errors.get('description')[0]

        return render(request, 'tracker/trackers.html', fields)


class TrackerDetailView(generic.DetailView):
    model = Track
    template_name = 'tracker/tracker.html'

    def get_context_data(self, **kwargs):
        labels = []
        data = []
        context = super(TrackerDetailView, self).get_context_data(**kwargs)
        records = Record.objects.filter(track__id=context['track'].id)

        for record in records:
            labels.append(record.date.strftime("%Y-%m-%d"))
            data.append(record.value)

        context['chart_labels'] = labels
        context['chart_data'] = data
        context['records'] = records
        context['record_form'] = RecordForm()
        return context


def add_record(request, tracker_id):
    new_record_form = RecordForm(request.POST)
    track = Track.objects.get(pk=tracker_id)
    if request.method == 'POST' and new_record_form.is_valid():
        try:
            record = Record()
            record.track = track
            record.value = request.POST['value']
            record.date = request.POST['datetime']
            record.note = request.POST['note']
            record.save()
        except ValueError:
            return render(request, 'tracker/tracker.html', {
                'track': track,
                'record_form': RecordForm(),
                'form_error': "Error adding record"
            })

        return HttpResponseRedirect(reverse('tracker:tracker_detail', args=(tracker_id,)))
    else:
        records = Record.objects.filter(track__id=track.id)
        fields = {
            'track': track,
            'record_form': new_record_form,
            'records': records,
        }
        if new_record_form.errors.get('value'):
            fields['value_error'] = new_record_form.errors['value'][0]
        if new_record_form.errors.get('datetime'):
            fields['datetime_error'] = new_record_form.errors['datetime'][0]
        return render(request, 'tracker/tracker.html', fields)

###############
# REST APIs
###############


@permission_classes((AllowAny, ))
class TrackerList(viewsets.ModelViewSet):
    queryset = Track.objects.all()
    serializer_class = TrackSerializer


@permission_classes((AllowAny, ))
class RecordList(viewsets.ModelViewSet):
    queryset = Record.objects.all()
    serializer_class = RecordSerializer

tracker/templates/tracker/tracker.html
<!DOCTYPE html>
<html lang="en">

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Trackers Page - training-python</title>
    <meta charset="utf-8"/>
    {% load static %}
    <link rel="stylesheet" type="text/css">
</head>

<body class="body" style="background-color:#f6f6f6">

{%  include "home/navbar.html"  %}

<div class="container">
    <div class="jumbotron">
        {% if track %}
            <h2>{{ track.name }}</h2>
            <h5>Description: {{ track.description }}</h5>
            <p>Unit: {{ track.unit }}</p>
            <hr />
            {% if user.is_authenticated %}
                <div>
                    <form action="{% url 'tracker:tracker_create_record' track.id %}" method="post">
                        {% csrf_token %}
                        {% if form_error %}
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <span class="text-danger">{{ form_error }}</span>
                                </div>
                            </div>
                        {% endif %}
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                <label for="{{ record_form.value.id_for_label }}">Value: </label>
                                {{ record_form.value }}
                                <div class="text-danger">{{ value_error }}</div>
                            </div>
                            <div class="form-group col-md-3">
                                <label for="{{ record_form.date.id_for_label }}">Date: </label>
                                {{ record_form.datetime }}
                                <div class="text-danger">{{ datetime_error }}</div>
                            </div>
                            <div class="form-group col-md-3">
                                <label for="{{ record_form.note.id_for_label }}">Note: </label>
                                {{ record_form.note }}
                                <div class="text-danger">{{ note_error }}</div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary" value="Add">
                    </form>
                </div>
                <hr />
            {% endif %}
            {% if records %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Value</th>
                        <th scope="col">Date</th>
                        <th scope="col">Note</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for record in records %}
                        <tr>
                            <td>{{ record.value }}</td>
                            <td>{{ record.date|date:"Y-m-d H:i" }}</td>
                            <td>{{ record.note }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <hr />
                <canvas id="tracker-chart"></canvas>
                <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
                <script>
                    const trackLineChartConfig = {
                        type: 'line',
                        data: {
                            datasets: [{
                                data: {{ chart_data|safe }},
                                label: '{{ track.unit }}'
                            }],
                            labels: {{ chart_labels|safe }}
                        },
                        options: {
                            responsive: true
                        }
                    };

                    window.onload = function() {
                        const ctx = document.getElementById('tracker-chart').getContext('2d')
                        window.lineChart = new Chart(ctx, trackLineChartConfig);
                    };
                </script>
                <hr />
            {% else %}
                <h3>No records found</h3>
            {% endif %}
        {% else %}
            <h2>No tracker found</h2>
        {% endif %}
    </div>
</div>
</body>

</html>

tracker/templates/tracker/trackers.html
<!DOCTYPE html>
<html lang="en">

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Trackers Page - training-python</title>
    <meta charset="utf-8"/>
    {% load static %}
    <link rel="stylesheet" type="text/css">
</head>

<body class="body" style="background-color:#f6f6f6">

{%  include "home/navbar.html"  %}

<div class="container">
    <div class="jumbotron">
        <h1>Trackers</h1>
        {% if user.is_authenticated %}
            <div>
                <form action="{% url 'tracker:create_tracker' %}" method="post">
                    {% csrf_token %}
                    {% if form_error %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <span class="text-danger">{{ form_error }}</span>
                            </div>
                        </div>
                    {% endif %}
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label for="{{ form.name.id_for_label }}">Name: </label>
                            {{ form.name }}
                            <div class="text-danger">{{ name_error }}</div>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="{{ form.unit.id_for_label }}">Unit: </label>
                            {{ form.unit }}
                            <div class="text-danger">{{ unit_error }}</div>
                        </div>
                        <div class="form-group col-md-7">
                            <label for="{{ form.description.id_for_label }}">Description: </label>
                            {{ form.description }}
                            <div class="text-danger">{{ description_error }}</div>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Create">
                </form>
            </div>
            <hr />
        {% endif %}
        {% if trackers_list %}
            <ul id="trackers-list" class="list-group">
                {% for tracker in trackers_list %}
                    <li class="list-group-item"><a
                            href="{% url 'tracker:tracker_detail' tracker.id %}">{{ tracker.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>No trackers</h3>
        {% endif %}
    </div>
</div>
</body>

</html>