core/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'core'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

notes/urls.py
from django.urls import path

from . import views, forms

app_name = "notes"
urlpatterns = [
    path('user', views.UserNotesView.as_view(), name='user_notes'),
    path('add', forms.note_add, name='note_add'),
    path('delete/<int:note_id>', views.note_delete, name='note_delete')
]

training/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from core.views import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='home/login.html', authentication_form=LoginForm),
        name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('weather/', include('weather_statistics.urls')),
    path('tracker/', include(('tracker.urls', 'tracker'), namespace='tracker'))
]

notes/models.py
from datetime import datetime

from django.conf import settings
from django.db import models
from django.db.models import QuerySet


class Note(models.Model):
    created = models.DateTimeField('created')
    modified = models.DateTimeField('modified', auto_now_add=True, blank=False)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=300)
    due = models.DateTimeField('due', blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def fill(self, data, user):
        self.user = user
        self.title = data['title']
        self.content = data['content']
        self.due = data['due']
        self.created = datetime.now()

    def __str__(self):
        return "id: {}, title: {}, content: {}, user: '{}'" \
            .format(self.pk, self.title, self.content, self.user.__str__())


class NoteQuerySet(QuerySet):

    @staticmethod
    def get_user_past_due_notes(user):
        now = datetime.now()
        past_due_notes = Note.objects.filter(user__id=user.id, due__lt=now)
        return past_due_notes.all()

notes/forms.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render

from notes.models import Note


class NoteForm(forms.Form):
    title = forms.CharField(max_length=50, min_length=3)
    content = forms.CharField(max_length=300)
    due = forms.DateTimeField(
        input_formats=['%Y-%m-%d %H:%M',
                       '%Y-%m-%d'],
        required=False
    )


def note_add(request):
    submitted = False
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note_data = form.cleaned_data
            note = Note()
            note.fill(note_data, request.user)
            note.save()
            return HttpResponseRedirect('/notes/user?submitted=True')
        else:
            errors = form.errors
            form = NoteForm()
            if 'submitted' in request.GET:
                submitted = True

        return render(request, 'notes/user_notes.html', {'form': form, 'submitted': submitted, 'errors': errors})

notes/views.py
from datetime import datetime

from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import ListView, TemplateView

from notes.forms import NoteForm
from notes.models import Note
from notes.utils import NoteUtils


class UserNotesView(ListView):
    template_name = 'notes/user_notes.html'
    context_object_name = 'user_notes'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('/')
        return super().get(self, request, *args, **kwargs)

    def get_queryset(self):
        user_id = self.request.user.pk
        user_notes = Note.objects.filter(user__id=user_id)
        return user_notes

        # note = Note()
        # note.title = 'Note Title'
        # note.content = 'Note content test Note content test Note content test Note content test'
        # note.created = datetime.now()
        #
        # notes = []
        # notes.append(note)
        # notes.append(note)
        # return notes

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        NoteUtils.context_add_user_past_due_notes(context, self.request)
        context['submitted'] = 'submitted' in self.request.GET
        context['form'] = NoteForm()
        return context


def note_delete(request, note_id):
    if not request.user.is_authenticated:
        return redirect('/')
    note = Note.objects.filter(pk=note_id)
    note.delete()
    return redirect('/notes/user')

notes/templates/notes/notifications_reminder.html
<a href="{% url 'notes:user_notes' %}" type="button" class="btn btn-primary">
    Notifications <span class="badge badge-danger">{{ notes_due_quantity }}</span>
</a>

notes/templates/notes/user_notes.html
<!DOCTYPE html>
<html lang="en">

{% load socialaccount %}
{% providers_media_js%}

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Users - training-python</title>
    <meta charset="utf-8"/>
</head>

<body class="body" style="background-color:#f6f6f6">
{% include "home/navbar.html" %}
<div class="container">
    <div class="jumbotron">
        <h2>{{ user.username }}</h2>
        <hr/>
        {% if submitted %}
        <div class="alert alert-success" role="alert">
            Note added!
        </div>
        {% endif %}
        <h5>Create new note</h5>
        <form class="needs-validation" action="add" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-8">
                    <input type="text" class="form-control" placeholder="Note Title" name="title" id="id_title"
                           required>
                    {% if errors.title %}
                    <div class="invalid-feedback" style="display: block">
                        {{ errors.title.0 }}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group col-md-3">
                    <input type="text" class="form-control" name="due" id="id_due" placeholder="Due Date (Optional)">
                    {% if errors.due %}
                    <div class="invalid-feedback" style="display: block">
                        {{ errors.due.0 }}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group col-md-1">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Note content" name="content" id="id_content"
                       required>
                {% if errors.content %}
                <div class="invalid-feedback" style="display: block">
                    {{ errors.content.0 }}
                </div>
                {% endif %}
            </div>
        </form>
        <hr/>
        <div class="card-deck">
            {% for note in user_notes %}
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">{{ note.title }}</h5>
                    <hr/>
                    <p class="card-text">{{ note.content }}</p>
                    {% if note.due %}
                    <p class="card-text text-danger">Due: {{ note.due | date:"Y-m-d H:i" }}</p>
                    {% endif %}
                    <p class="card-footer">{{ note.created | date:"Y-m-d H:i"}}</p>
                    <hr/>
                    <a href="{% url 'notes:note_delete' note.id %}">Delete</a>
                </div>
            </div>
            {% empty %}
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">No notes</h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</body>

</html>