core/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'core'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

notes/urls.py
from django.urls import path

from . import views, forms

app_name = "notes"
urlpatterns = [
    path('user', views.UserNotesView.as_view(), name='user_notes'),
    path('add', forms.note_add, name='note_add'),
    path('delete/<int:note_id>', views.note_delete, name='note_delete')
]

tracker/urls.py
from django.urls import include, path
from rest_framework import routers

from tracker import views

app_name = 'tracker'

router = routers.DefaultRouter()
router.register(r'trackers', views.TrackerList)
router.register(r'records', views.RecordList)

urlpatterns = [
    path('', views.TrackersView.as_view(), name='trackers'),
    path('create', views.create_tracker, name='create_tracker'),
    path('<int:pk>/', views.TrackerDetailView.as_view(), name='tracker_detail'),
    path('<int:tracker_id>/create_record', views.add_record, name='tracker_create_record'),
    path('api/', include(router.urls)),
]

training/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from core.views import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='home/login.html', authentication_form=LoginForm),
        name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('weather/', include('weather_statistics.urls')),
    path('tracker/', include(('tracker.urls', 'tracker'), namespace='tracker'))
]

core/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self):
        return "id: {}, username: {}, email: {}".format(self.pk, self.username, self.email)

    def create_user_configuration(self):
        configuration = UserConfiguration.objects.filter(user__id=self.pk)
        if configuration.count() == 0:
            configuration = UserConfiguration()
            configuration.user = self
            configuration.save()

    def get_user_configuration(self):
        configuration = UserConfiguration.objects.filter(user__id=self.pk)
        return configuration.get()


class Configuration:
    DEFAULT_CONFIGURATION = dict({'visible': True})


class UserConfiguration(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    configuration = JSONField(null=False, blank=False, default=Configuration.DEFAULT_CONFIGURATION)

    def __str__(self):
        return "user: '{}', configuration: {}".format(self.user.__str__(), self.configuration)

core/views.py
# Create your views here.
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, Group
from django import forms
from django.views.generic import TemplateView
from rest_framework import viewsets

from core.serializers import UserSerializer, GroupSerializer


class IndexView(TemplateView):
    template_name = 'home/index.html'

    message = 'Hello World'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = self.message
        return context


# Rest endpoint
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control'}
    ))

core/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Home Page - training-python</title>
    <meta charset="utf-8"/>
    {% load static %}
    <link rel="stylesheet" type="text/css">
</head>

<body class="body" style="background-color:#f6f6f6">

{%  include "home/navbar.html"  %}

<div class="container">
    <div class="jumbotron">
        <h1>{{ msg }}</h1>
        {% buttons %}
            <button class="btn btn-primary">Button</button>
        {% endbuttons %}
    </div>
</div>
</body>

</html>

core/templates/home/login.html
<!DOCTYPE html>
<html lang="en">

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Home Page - training-python</title>
    <meta charset="utf-8"/>
    {% load static %}
    <link rel="stylesheet" type="text/css">
    <link rel="stylesheet"  href="{%  static  'css/login.css'  %}">
</head>

<body class="body" style="background-color:#f6f6f6">


<div class="container">
    <!-- Login Form -->
    <div class="login-form">
        <form method="post">
            <h2 class="text-center">Log in</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </div>
            <div class="clearfix">
                <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
                <a href="#" class="float-right">Forgot Password?</a>
            </div>
        </form>
        <p class="text-center"><a href="#">Create an Account</a></p>
    </div>

</div>
</body>

</html>

core/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">python-training</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link active" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'tracker:trackers' %}">Tracking</a>
        </div>
        {% if not user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'login' %}" role="button">Login</a>
        {% else %}
            <a class="btn btn-secondary" href="" role="button">Logged as: {{ user.username }}</a>
            <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
        {% endif %}
    </div>
</nav>

core/templates/home/user.html
<!DOCTYPE html>
<html lang="en">

{% load socialaccount %}
{% providers_media_js%}

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Users - training-python</title>
    <meta charset="utf-8"/>
</head>

<body class="body" style="background-color:#f6f6f6">
{% include "home/navbar.html" %}
<div class="container">
    <div class="jumbotron">
        <h2>{{ user.username }}</h2>
        {% if request.user.id == request.resolver_match.kwargs.pk %}
        <p>
            User <a href="{% url 'core:user_configuration' %}">configuration</a>
        </p>
        <p>
            Your <a href="{% url 'notes:user_notes' %}">notes</a>
        </p>
        {% endif %}
        <hr/>
        <p>Email: {{ user.email }}</p>
        <hr/>
        <h2>Configuration</h2>
        {% for key, value in user.get_user_configuration.configuration.items %}
            <p>{{key}} : {{ value }}</p>
        {% endfor %}
    </div>
</div>
</body>

</html>

core/templates/home/user_configuration.html
<!DOCTYPE html>
<html lang="en">

{% load socialaccount %}
{% providers_media_js%}

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Users - training-python</title>
    <meta charset="utf-8"/>
</head>

<body class="body" style="background-color:#f6f6f6">
{% include "home/navbar.html" %}
<div class="container">
    <div class="jumbotron">
        <h2>Configuration</h2>
    </div>
</div>
</body>

</html>

core/templates/home/users.html
<!DOCTYPE html>
<html lang="en">

{% load socialaccount %}
{% providers_media_js%}

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <title>Users - training-python</title>
    <meta charset="utf-8"/>
</head>

<body class="body" style="background-color:#f6f6f6">
{% include "home/navbar.html" %}
<div class="container">
    <div class="jumbotron">
        <h2>Users</h2>
        {% if users %}
        <ul>
            {% for user in users %}
            <li>{{ user.username }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No users registered.</p>
        {% endif %}
    </div>
</div>
</body>

</html>